server:
  port: "8083"

mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "001020"
  dbname: "hmdp"

redis:
  host: "localhost"
  port: "6379"
  password: "001020"
  db: 0

grpc:
  port: "50053"

etcd:
  endpoints:
    - "localhost:2379"
  service:
    host: "127.0.0.1"
    name: "content-service"
    ttl: 10
  user_service:
    name: "user-service"
