server:
  port: "8081"

mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "001020"
  dbname: "hmdp"

redis:
  host: "127.0.0.1"
  port: "6379"
  password: "001020"
  db: 0

grpc:
  port: "50051"

token:
  secret: "your-secret-key"
  access_token_ttl: 3600
  refresh_token_ttl: 86400
